### ISSUE TITLE
Filesize of the chosen image from gallery is bigger then real one on IOS

### ISSUE THREAD

**Issue by heavyskyl** [react-native-image-picker/react-native-image-picker#1419]
# Bug report

## Summary

Filesize of the chosen image from gallery is bigger then real one on IOS

Old reported issue that was auto-closed: https://github.com/react-native-community/react-native-image-picker/issues/514

## Environment info

System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 339.55 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.0.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: javac 14 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ^0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 2.3.3

## Steps to reproduce

steps to reproduce:
1. download this image https://drive.google.com/drive/folders/1EfouUVxVVcV7YtzgCZuw23udlUvcoxGd?usp=sharing
2. pick an image from gallery and check it's size ( on ios emulator or on ios real device )

current result:
for some images file size is 2x, 3x bigger then they are
image uploading request size is also 2x, 3x bigger then it should be

expected result:
image size will be correct one

Notes: it was reproduced on iPhone 6s, 7, X, Xs Max, different iPhone emulators by different people in my team

**Comment by vinhnglx** [comment]
@heavyskyl 

I'm also having the same issue on iOS simulators, the original image was 500kb, but the moment I choose the image from the gallery, the image size is 2mb. 

I went to check, and then I found the library created a new copy image with increased size and use it - the library doesn't use the original image from the gallery.

The `quality` option can be used to decrease the size, but I don't think it's the solution.

**Comment by zhangsl1987** [comment]
does is has any solutions?

**Comment by vinhnglx** [comment]
@zhangsl1987 use the `origURL` attribute. It will return the URL of the original asset in the photo library if it exists.

**Comment by Achilles718611** [comment]
I got the same error.
The problem is only appeared when I test with phone.
When I test with simulator, I can't see any error.

**Comment by ravirajn22** [comment]
Version 2.x.x is not longer supported, please upgrade to 3.x.x
I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it.

**Comment by khalidahmedshalabi** [comment]
> Version 2.x.x is not longer supported, please upgrade to 3.x.x
> I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it.

Still occurs on v3.1.3 @ravirajn22 
RN v0.63.4
Emulator iPhone 8
iOS 14.3

**Comment by ravirajn22** [comment]
@khalidahmedshalabi what options you provide in the API, paste your code. How do check that the file size has increased provide more details.

**Comment by khalidahmedshalabi** [comment]
Regular use
``` javascript
handleImagePickerResponse = (response) => {
		console.log(response);

		if (response.didCancel) {

		}
		else if (response.error) {

		}
		else {
			this.setState({ imageUri: response.uri })
		}
	}

	pickImage = () => {
		const options = {
			mediaType: 'photo',
			//quality: 0.8,
		};

		launchImageLibrary(options, this.handleImagePickerResponse)
	}
```

File size
![image](https://user-images.githubusercontent.com/4519116/105507996-850d5e00-5cd4-11eb-9e39-9491289a146f.png)


I get the correct size on Android though

**Comment by Achilles718611** [comment]
Problem is IOS.
Are you sure it's fixed?

**Comment by khalidahmedshalabi** [comment]
It's not @Achilles718611

**Comment by likashefqet** [comment]
This issue is still happening on version 4.

Tested with:
  - library versions: 4.1.1 & 4.6.0.
  - iOS versions: 14.4, 15.1 & 15.2 (iPhone 11 - real device)
  - iOS versions: 14.4, 15.1 & 15.2 (iPhone 8, X, 12, 13 simulators)
  - different images of different sizes
