### ISSUE TITLE
[🐛]  Broken Orientation

### ISSUE THREAD

**Issue by Standin-Alone** [react-native-image-picker/react-native-image-picker#2022]
### Description

Explain the bug in as much detail as possible

### How to repeat issue and example

- step to reproduce the issue
- ...

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
- React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
- Platform: [FILL THIS OUT: iOS, Android, or both?]
- Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
- Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

**Comment by MEsteves22** [comment]
Hello! 

When I take a photo with the camera, the picture rotates 90º.

This only happens on iOS. 

The problem started to happen on version 4.8.5. If I downgrade to version 4.8.4, everything is fine. Thus, maybe the problem was introduced in this [PR](https://github.com/react-native-image-picker/react-native-image-picker/pull/2006.) since these were the only changes done on 4.8.5.

Image picker version: 4.10.0
React Native version: 0.67.4
Platform: iOS
Development Operating System: MacOS
Dev tools: xCode

**Comment by gayanwiharagoda** [comment]
I have face the same issue. fix was the add maxWith and maxHight. But not sure what is the magic behind it.

**Comment by levino** [comment]
I have this issue as well. @Standin-Alone please update the issue description with the way more helpful [information](https://github.com/react-native-image-picker/react-native-image-picker/issues/2022#issuecomment-1234040053) by @MEsteves22 

Downgrading to `4.8.4` fixed the issue for me.

**Comment by Letty** [comment]
Thank you, the downgrade worked for me as well.

**Comment by DavidLaikaCo** [comment]
> I have face the same issue. fix was to add maxWith and maxHight. But not sure what is the magic behind it.

do you have an example of how to do it? that solution would only be from the front part to send it to a server if it sends it flipped?

**Comment by DavidLaikaCo** [comment]
> Thank you, the downgrade worked for me as well.

do you have an example of how to do it? that solution would only be from the front part to send it to a server if it sends it flipped?

**Comment by LazyAfternoons** [comment]
Same issue here and I can't downgrade 'cause I'm targeting Android 13.

**Comment by GiovanniVisentiniCasavo** [comment]
I fix the problem also requesting a specific quality, for example 0.9 
this will force to generate the jpg image, and overwrite the buggy images with the correct one

**Comment by LazyAfternoons** [comment]
> I fix the problem also requesting a specific quality, for example 0.9 this will force to generate the jpg image, and overwrite the buggy images with the correct one

Thanks for the workaround and the PR.

**Comment by ArkanRomanPango** [comment]
@gayanwiharagoda maxWidth and maxHeight fixed for ios but for android the same...

**Comment by MEsteves22** [comment]
@GiovanniVisentiniCasavo thank you for your help! The workaround is working for me as well as your PR.

**Comment by virginiab10** [comment]
I'm having the same issue, adding the quality prop fixed it but I hope the maintainers will fix the bug soon! 🙏🏼
Thank you @GiovanniVisentiniCasavo !

**Comment by Johan-dutoit** [comment]
Should be fixed with this merge https://github.com/react-native-image-picker/react-native-image-picker/pull/2036

https://github.com/react-native-image-picker/react-native-image-picker/pull/2036#issuecomment-1312426308

**Comment by samskinner32** [comment]
I'm on version "5.0.0" of the library and this issue is still happening for me when taking portrait pictures with the camera - they are rotated 90 degrees. Landscape works with the camera and both portrait/landscape works with the gallery.

Happens with both iOS and Android.

I am using the following CameraOptions:
`const uploadOptions: CameraOptions = {
    cameraType: 'front',
    includeBase64: true,
    mediaType: 'photo',
    presentationStyle: 'formSheet',
    quality: 0.4,
  };`

**Comment by jihokim2** [comment]
It happens only in Android. Please fix it fast

**Comment by tfsjohan** [comment]
This still is an issue on Android. Works better on emulator than real device (Pixel 4 in my case). 

Images from library or camera is rotated 90 degrees wrong. "includeExtra" does not include any information about the rotation, so it's very hard to fix with other libraries or server side.

**Comment by johnernest02-automanager** [comment]
Anyone able to fix this?
